apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadtwqd4087-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadtwqd4087-tenant-component
    app.kubernetes.io/part-of: loadtwqd4087-tenant-app
  name: loadtwqd4087-tenant-component
  namespace: loadtwqd4087-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadtwqd4087-tenant-component
    weight: null
status: {}
